FROM maven:3.9.4-eclipse-temurin-17

WORKDIR /app

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Download all dependencies (to avoid downloading during each run)
RUN mvn dependency:resolve

# Run Maven tests

CMD ["mvn", "test"]






