# Spring application name
spring.application.name=SwiftCode
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=123
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Optional Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable H2 database (if it's auto-configured)
spring.test.database.replace=NONE
spring.datasource.data=init:setup_database.sql
